export enum OrderType {
  CARD = 'CARD',
  CASH = 'CASH',
  TRANSFER = 'TRANSFER',
}

export enum ItemType {
  FOOD = 'FOOD',
  DRINK = 'DRINK',
  SNACK = 'SNACK',
  DESSERT = 'DESSERT',
}

export enum MealCategory {
  RICE = 'RICE',
  SWALLOW = 'SWALLOW',
  SOUP = 'SOUP',
  STEW = 'STEW',
  BEANS = 'BEANS',
  SNACK = 'SNACK',
  GRILL = 'GRILL',
  SIDES = 'SIDES',
  STREET_FOOD = 'STREET_FOOD',
  BREAKFAST = 'BREAKFAST',
  PASTA = 'PASTA',
  PIZZA = 'PIZZA',
  BURGER = 'BURGER',
  SANDWICH = 'SANDWICH',
  DESSERT = 'DESSERT',
  SOUP_FOREIGN = 'SOUP_FOREIGN',
  SEAFOOD = 'SEAFOOD',
  CHICKEN = 'CHICKEN',
  BEEF = 'BEEF',
  LAMB = 'LAMB',
  VEGAN = 'VEGAN',
  DRINK = 'DRINK',
}

export enum MealTag {
  SPICY = 'SPICY',
  VEGAN = 'VEGAN',
  GLUTEN_FREE = 'GLUTEN_FREE',
  DAIRY_FREE = 'DAIRY_FREE',
  HALAL = 'HALAL',
  LOCAL = 'LOCAL',
  CONTINENTAL = 'CONTINENTAL',
  PARTY_MEAL = 'PARTY_MEAL',
  QUICK_BITE = 'QUICK_BITE',
  FAMILY_SIZE = 'FAMILY_SIZE',
  SEAFOOD = 'SEAFOOD',
  GRILLED = 'GRILLED',
  FRIED = 'FRIED',
  SOUPY = 'SOUPY',
  SWEET = 'SWEET',
  SAVOURY = 'SAVOURY',
}
