export enum OrderType {
  CARD = 'CARD',
  CASH = 'CASH',
  TRANSFER = 'TRANSFER',
}

export enum ItemType {
  FOOD = 'FOOD',
  DRINK = 'DRINK',
  SNACK = 'SNACK',
  DESSERT = 'DESSERT',
  SIDE = 'SIDE',
  COMBO = 'COMBO',
  ADDON = 'ADDON',
}

export enum MealTag {
  SPICY = 'SPICY',
  VEGAN = 'VEGAN',
  GLUTEN_FREE = 'GLUTEN_FREE',
  DAIRY_FREE = 'DAIRY_FREE',
  HALAL = 'HALAL',
  LOCAL = 'LOCAL',
  CONTINENTAL = 'CONTINENTAL',
  PARTY_MEAL = 'PARTY_MEAL',
  QUICK_BITE = 'QUICK_BITE',
  FAMILY_SIZE = 'FAMILY_SIZE',
  SEAFOOD = 'SEAFOOD',
  GRILLED = 'GRILLED',
  FRIED = 'FRIED',
  SOUPY = 'SOUPY',
  SWEET = 'SWEET',
  SAVOURY = 'SAVOURY',
  POPULAR = 'POPULAR',
  NEW = 'NEW',
  HEALTHY = 'HEALTHY',
  PROTEIN_RICH = 'PROTEIN_RICH',
  LOW_CALORIE = 'LOW_CALORIE',
}

export enum DatabaseErrorCodes {
  UNIQUE_VIOLATION = '23505',
  FOREIGN_KEY_VIOLATION = '23503',
  NOT_NULL_VIOLATION = '23502',
  CHECK_VIOLATION = '23514',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  PREPARING = 'PREPARING',
  PREPARED = 'PREPARED',
  DISPATCHED = 'DISPATCHED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}
